### ISSUE TITLE
Generator_failed error

### ISSUE THREAD

**Issue by peter-de-boer** [gutschilla/elixir-pdf-generator#86]
I am trying to use elixir-pdf-generator in my web app.
First I have tried to use it with wkhtmltopdf, but it seems it does not handle all css correctly
So, I am now using it with Chrome-headless/Puppeteer.
I have installed it according to:

> Eventually, if you are using Phoenix and you would like to have your npm packages installed localy, within the `/assets/node_modules` directory, simply run `npm install chrome-headless-render-pdf puppeteer` within `assets/node_modules` and pass `prefer_local_executable: true` option when generating the PDF like this:
> 
> PdfGenerator.generate(url, generator: :chrome, prefer_local_executable: true)

Bit if I try it with an existing url, I get:

```
[debug] {"/usr/local/bin/node", ["/home/peter/bw/_build/dev/lib/pdf_generator/priv/node_modules/chrome-headless-render-pdf/dist/cli/chrome-headless-render-pdf.js", "--url", "http://localhost:4000/factuur/test", "--pdf", "/tmp/MlUkqisz.pdf", "--paper-width", "8.26772", "--paper-height", "11.695"]}
{:error,
 {:generator_failed,
  "internal/modules/cjs/loader.js:883\n  throw err;\n  ^\n\nError: Cannot find module '/home/peter/bw/_build/dev/lib/pdf_generator/priv/node_modules/chrome-headless-render-pdf/dist/cli/chrome-headless-render-pdf.js'\n    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)\n    at Function.Module._load (internal/modules/cjs/loader.js:725:27)\n    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)\n    at internal/main/run_main_module.js:17:47 {\n  code: 'MODULE_NOT_FOUND',\n  requireStack: []\n}\n"}}
```

Any ideas?

**Comment by yugandharc9** [comment]
Hi Peter was facing same problem solved by

`
cd deps/pdf_generator/priv && npm install`

In my mix.exs 

      { :pdf_generator, ">=0.6.2" },

**Comment by yugandharc9** [comment]
Used like this 

     PdfGenerator.generate(html,page_size: "A3", delete_temporay: true,generator: :chrome, prefer_local_executable: true)

**Comment by gutschilla** [comment]
Thanks for pointing that out. This seems to be an incompatibility with newer Phoenixes
