### ISSUE TITLE
Heroku: (ErlangError) Erlang error: :enoent

### ISSUE THREAD

**Issue by fkumro** [gutschilla/elixir-pdf-generator#88]
I've had to change the buildpack which provided `wkhtmltopdf` and as a result, I now receive the following error when generating a PDF.

```shell
** (ErlangError) Erlang error: :enoent
    (elixir 1.12.3) lib/system.ex:1041: System.cmd("bin/wkhtmltopdf", ["--page-size", "A4", "/tmp/ah9YnJPg.html", "/tmp/ah9YnJPg.pdf"], [stderr_to_stdout: true])
    (pdf_generator 0.6.2) lib/pdf_generator.ex:141: PdfGenerator.generate/2
```

The buildpack I used for the wkhtmltopdf binary is: https://github.com/notvad/wkhtmltopdf-buildpack

The absolute path to the binary is configured:

```elixir
config :pdf_generator,
  wkhtml_path: "bin/wkhtmltopdf"
```

I have verified the binary exists:

```elixir
iex(1)> System.cmd("ls",["bin"])
{"wkhtmltopdf\n", 0}
```

`:enoent` sounds like the generated PDF file doesn't exist. I was able to locate a test source HTML file that was used, in the `/tmp` directory. This rules out the error coming from the source file.

```elixir
iex(2)> System.cmd("ls",["/tmp"])
{"appsignal\nappsignal.log\nmask\n", 0}

iex(3)> html = "<html><body><p>Hi there!</p></body></html>"
"<html><body><p>Hi there!</p></body></html>"

iex(4)> {:ok, filename}    = PdfGenerator.generate(html, page_size: "A5")
** (ErlangError) Erlang error: :enoent
    (elixir 1.12.3) lib/system.ex:1041: System.cmd("bin/wkhtmltopdf", ["--page-size", "A5", "/tmp/P2XVAVUC.html", "/tmp/P2XVAVUC.pdf"], [stderr_to_stdout: true])
    (pdf_generator 0.6.2) lib/pdf_generator.ex:141: PdfGenerator.generate/2

iex(4)> System.cmd("ls",["/tmp"])
{"P2XVAVUC.html\nappsignal\nappsignal.log\nmask\n", 0}
```

No other error output is provided, this leads me to believe there is something wrong with the binary? Thoughts?

**Comment by fkumro** [comment]
Solution: The `:enoent` error is caused by the configured path to `wkhtmltopdf`. Updating the path to `/app/bin/wkhtmltopdf` resolved the issue.
