### ISSUE TITLE
Erlang error, "invalid port name"

### ISSUE THREAD

**Issue by mxgrn** [gutschilla/elixir-pdf-generator#95]
Running PdfGenerator from a Docker container:

```
Erlang/OTP 25 [erts-13.0.4] [source] [64-bit] [smp:1:1] [ds:1:1:10] [async-threads:1] [jit:ns]

Interactive Elixir (1.14.0) - press Ctrl+C to exit (type h() ENTER for help)
iex(app@elixir-1.local)1> PdfGenerator.generate {:url, "http://google.com"}, page_size: "A5"
** (ErlangError) Erlang error: :enoent:

  * 1st argument: invalid port name

    :erlang.open_port({:spawn_executable, '/usr/bin/xvfb-run'}, [:stderr_to_stdout, :use_stdio, :exit_status, :binary, :hide, {:args, ["/usr/local/bin/wkhtmltopdf", "--page-size", "A5", "http://google.com", "/tmp/jnnJSZEW.pdf"]}])
    (elixir 1.14.0) lib/system.ex:1064: System.do_cmd/3
    (pdf_generator 0.6.2) lib/pdf_generator.ex:141: PdfGenerator.generate/2
    iex:1: (file)
iex(app@elixir-1.local)1>
01:01:39.005 [debug] {"/usr/bin/xvfb-run", ["/usr/local/bin/wkhtmltopdf", "--page-size", "A5", "http://google.com", "/tmp/jnnJSZEW.pdf"]}
```

When I run `wkhtmltopdf` directly (from the container's bash), it does produce a pdf (I haven't checked whether the PDF itself is correct, though).

Please, let me know if you need any additional info!

**Comment by mxgrn** [comment]
Apparently, `/usr/bin/xvfb-run` simply did not exist.
